[workspace]
resolver = "2"
members = [
    "kernel",
    "servers/sexdisplay",
    "servers/sexshop",
    "servers/silk-shell",
    "servers/sexinput",
    "servers/sexusb",
    "servers/silkbar",
    "servers/linen",
    "apps/sexdrive",
    "purple-scanout",
    "crates/sex-pdx",
    "crates/sex-graphics",
    "crates/silkbar-model",
]
[workspace.package]
license = "GPL-3.0-only"

[profile.release]
panic = "abort"
