[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-sex.json"

[target.x86_64-sex]
rustflags = [
    "-C", "linker=sex-ld",
    "-C", "target-cpu=skylake",
    "-C", "link-arg=-Tkernel/linker.ld",
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
]
